### ISSUE TITLE
events.js:141       throw er;

### ISSUE THREAD

**Issue by Jan-Jan** [GetExpert/redux-blog-example#11]
redux-blog-example used to work great. 

Now when I run

```
npm run dev
```

I get the following error:

```
23 Sep 11:10:11 - [nodemon] starting `babel-node ./api`
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::1337
```

**Comment by Jan-Jan** [comment]
I did a

```
rm -rf
npm install
```

The error remains, but now the servers start up?

**Comment by faergeek** [comment]
Looks like server already running. Check output of this command:

```bash
ps aux | grep -i node
```

Output should be similar to:

```
<username> <PID>  <Some other things here> node <something else>
```

You should find needed `PID`s and `kill` it like that `kill <PID>`.

**Comment by Jan-Jan** [comment]
Thank you, that solved it.

**Comment by Xeroner** [comment]
So meaby give us solution???
