### ISSUE TITLE
How are you getting the router attached to the context in your components, like the SignupRoute?

### ISSUE THREAD

**Issue by mjhamm75** [GetExpert/redux-blog-example#12]
I am trying to follow some of the patterns that you have in your app, but I keep getting `undefined` for my `router` in my `handleSubmit`?  How is the `router` getting attached to the `context` in this example?

**Comment by faergeek** [comment]
You should add these lines into your component's class:
```javascript
static contextTypes = {
  router: React.PropTypes.object
}
```
then you can get router like this:
```javascript
render {
  const router = this.context.router;
  router.transitionTo(...);
}
```

But it really depends on what version of react-router you use.
This example uses 1.0.0-beta3.
In 1.0.0-rc1 there's no `router` in context, but there are `history` and `location`.

Anyway you could use [redux-router](https://github.com/rackt/redux-router) now.
It's just plug'n'play solution that glues together react-router and redux nicely :-)

**Comment by brennanerbz** [comment]
So in the newest version, if you wanted to change routes based on a state
change (e.g you publish a blog post), in the action creator you would use
history.pushState instead of router.transitionTo?

**Comment by faergeek** [comment]
Yes, I guess `react-router` should listen for changes on that object.
I've personally just decided to just use `redux-router` after 1.0.0-rc1 of `react-router` :-)

**Comment by brennanerbz** [comment]
Do you have a code snippet for more context? Trying to get my bearings
straight with routing in Redux.

**Comment by faergeek** [comment]
To get history you should define needed context in your class:
```javascript
static contextTypes = {
  history: React.PropTypes.object
}
```

And get it where needed and call [methods](https://github.com/rackt/history/blob/master/docs/GettingStarted.md#navigation):
```javascript
componentDidUpdate() {
  const history = this.context.history;
  history.pushState({ some: 'state' }, '/some/path');
}
```

**Comment by mjhamm75** [comment]
I do have the `contextTypes` set.  Here is the whole file:

```
class LoginContainer extends React.Component {
	static contextTypes = {
		router: React.PropTypes.object
	}

	handleLogin() {
		this.props.login();
		console.log("Router info:");
		console.log(this.context.router);
	}

	render() {
		return <Login handleLogin={this.handleLogin.bind(this)} />
	}
}

function mapPropsFromState(state) {
	return {
		login
	}
}

export default connect(mapPropsFromState)(LoginContainer);
```

In the `console.log(this.context.router), I get `undefined`.  I will check out `redux-router`, but I am just trying to understand your code.

**Comment by faergeek** [comment]
@mjhamm75 Can you tell which `react-router` version you have?

**Comment by mjhamm75** [comment]
`1.0.0-rc1`

**Comment by faergeek** [comment]
As I said there's no `router` in context for that version.
So you should follow that path
https://github.com/GetExpert/redux-blog-example/issues/12#issuecomment-143775485
