### ISSUE TITLE
npm start

### ISSUE THREAD

**Issue by zanjs** [GetExpert/redux-blog-example#18]
julauddeMacBook-Pro:redux-blog-example julaud$ npm start

> @ start /Users/www/react/redux/redux-blog-example
> NODE_ENV=production babel-node ./api & node . & wait

Warning: you are using an outdated format of React Transform configuration. Please update your configuration to the new format. See the Releases page for migration instructions: https://github.com/gaearon/babel-plugin-react-transform/releases

**Comment by faergeek** [comment]
Thanks, we'll fix it very soon.

**Comment by olegakbarov** [comment]
Got a  PR for that, but i can't handle the Travis :sweat_smile:
