### ISSUE TITLE
Set $PATH in Makefile

### ISSUE THREAD

**Issue by faergeek** [GetExpert/redux-blog-example#24]
The main thing is `PATH := $(shell npm bin):$(PATH)`.
`:=` is different from `=` because `:=` is not recursive and `=` is.

So we can replace lines like `$(ESLINT)` with just `eslint` and remove strings like `ESLINT = $(NB)/eslint` and `NB = ./node_modules/.bin` :-)

@olegakbarov Would you like to fix it?

**Comment by faergeek** [comment]
Probably we'd better to hardcode `PATH := ./node_modules/.bin:$(PATH)`.
`npm bin` is too slow.

**Comment by faergeek** [comment]
Other paths should probably use `:=` instead of `=`.

**Comment by olegakbarov** [comment]
Awesome, go for it.

**Comment by faergeek** [comment]
>@olegakbarov Would you like to fix it?

**Comment by olegakbarov** [comment]
No, thank you kindly.

**Comment by olegakbarov** [comment]
I just don't want to take pleasure of fixing it from you. I gotta appreciate that.

**Comment by faergeek** [comment]
@olegakbarov Such a great care :-P
