### ISSUE TITLE
Is it maintained?

### ISSUE THREAD

**Issue by faergeek** [GetExpert/redux-blog-example#25]
I'd like to be honest about the level of maintenance of this project)
http://isitmaintained.com/project/GetExpert/redux-blog-example

**Comment by olegakbarov** [comment]
We should write up roadmap for this project so fellow githubbers could participate.

**Comment by faergeek** [comment]
Yes, I'll write it soon :-)

**Comment by olegakbarov** [comment]
I appreciate it if you take a look at open PR's :wink:
