### ISSUE TITLE
'npm run build' is failing

### ISSUE THREAD

**Issue by anilapu** [GetExpert/redux-blog-example#8]
After `npm install` when I try to run `npm run build` it throws error

'BUNDLE' is not recognized as an internal or external command,
operable program or batch file.ows error

<pre>WIN7@ANUSH-PC /e/cronj/react-practice/redux-blog-example (master)
$ npm run build

> @ build e:\cronj\react-practice\redux-blog-example
> npm run build:server && npm run build:client

> @ build:server e:\cronj\react-practice\redux-blog-example
> BUNDLE=server NODE_ENV=production webpack

'BUNDLE' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "c:\\Program Files\\nodejs\\\\node.exe" "c:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "run" "build:server"
npm ERR! node v0.12.6
npm ERR! npm  v2.11.2
npm ERR! code ELIFECYCLE
npm ERR! @ build:server: `BUNDLE=server NODE_ENV=production webpack`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ build:server script 'BUNDLE=server NODE_ENV=production
webpack'.
npm ERR! This is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     BUNDLE=server NODE_ENV=production webpack
npm ERR! You can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     e:\cronj\react-practice\redux-blog-example\npm-debug.log

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v0.12.6
npm ERR! npm  v2.11.2
npm ERR! code ELIFECYCLE
npm ERR! @ build: `npm run build:server && npm run build:client`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ build script 'npm run build:server && npm run build:cli
ent'.
npm ERR! This is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build:server && npm run build:client
npm ERR! You can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     e:\cronj\react-practice\redux-blog-example\npm-debug.log </pre>

**Comment by olegakbarov** [comment]
Can't reproduce it because don't have Windows env. Wonder if anybody have same problem? (works fine for me on OS X)

**Comment by anilapu** [comment]
@olegakbarov I don't have OS X env

**Comment by anilapu** [comment]
@olegakbarov  I have tried on another windows env. It shows same error

**Comment by faergeek** [comment]
@anilapu We'll fix this a little later.

Fow now please take a look at this
http://superuser.com/questions/223104/setting-environment-variable-for-just-one-command-in-windows-cmd-exe

Scripts you may need are here
https://github.com/GetExpert/redux-blog-example/blob/master/package.json#L20-L30

**Comment by faergeek** [comment]
Sorry, currently we have no plans to support Windows.
